baseURL = "https://xue2zeng.github.io/"
languageCode = "en-us"
title = "xue.zeng blog"
description = "test"
pygmentsCodeFences = true
pygmentsUseClasses = true
summaryLength= 10

[author]
  name = "xue.zeng"

[[menu.main]]
  name = "About"
  weight = 50
  identifier = "about"
  url = "/about"

[Params]
 	useHLJS = true
 	dateFormat = "2006-01-02"
